### PR TITLE
npm --force install add-project-script globally

### LINKED ISSUE #80: add-project-script missing in (dev) dependencies?
## Describe the bug

`manage.py initial_sockpuppet` throws error during tutorial [https://sockpuppet.argpar.se/setup-django](https://sockpuppet.argpar.se/setup-django)

## To Reproduce

Just follow the instructions on https://sockpuppet.argpar.se/setup-django

## Expected behavior

There should be no errors

## Screenshots or reproduction
```
./manage.py initial_sockpuppet
Wrote to /home/christian/Projekte/reflex/package.json:

{
  "name": "reflex",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "Christian González <...@...at>",
  "license": "ISC"
}


/home/christian/.nvm/versions/node/v13.6.0/bin/add-project-script -> /home/christian/.nvm/versions/node/v13.6.0/lib/node_modules/add-project-script/dist/index.js
+ add-project-script@1.0.2
added 11 packages from 6 contributors in 1.014s
/bin/sh: Zeile 1: add-project-script: Kommando nicht gefunden.
Build and watch already in package.json, so skipping these
removed 11 packages in 0.199s
```

Maybe [add-project-script](https://www.npmjs.com/package/add-project-script) is missing and should be installed before (globally?) - this should be mentioned in the setup.

### Django-sockpuppet
- pypi: 0.5.0

### External tools

- Python: [e.g. 3.9]
- Django: [e.g. 3.5.1]
- OS: [Linux]

### PR DESCRIPTION
**Pull request by nerdoc**
overwrite existing files/links when re-installing an existing add-project-script library globally
fixes #80

### CODE REVIEW

**Comment by nerdoc** [comment]
The unittest (3.6,2.2) fails because of whitespace not related to this PR.

**Comment by jonathan-s** [comment]
If you rebase against master we can make sure that all tests pass, which they should now.

**Comment by nerdoc** [comment]
OMG. I pulled in the camelcase patch here. Bah - git is quirky sometimes (if you don't master it ...)

**Comment by nerdoc** [comment]
(I rebased on my own master ...)

**Comment by nerdoc** [comment]
I think it's easier if I close this patch and make a new one ;-)

**Pull request closed without merging**
