### PR TITLE
A reflex can access the context of the view it came from

### PR DESCRIPTION
**Pull request by jonathan-s**
# Type of PR (feature, enhancement, bug fix, etc.)
Feature. 

## Description
It may be desirable for a reflex to access the context of the view it came from. This feature provides a way for reflexes to be able to access that. 

## Why should this be added
Not being able to access the context from the view it came from can make it difficult to set up certain things in the reflex.  

## Checklist

- [x] Tests are passing
- [x] Documentation has been added or amended for this feature / update

### CODE REVIEW

**Comment by jonathan-s** [comment]
@JulianFeinauer you may be interested in seeing this.

**Comment by jonathan-s** [comment]
@JulianFeinauer Any preference in terms having this be a function or a property?

**Comment by JulianFeinauer** [comment]
Just one thing that came to my mind. With this setup... The context could be evaluated multiple times (at least 2 if you access it in the reflex, or)?

**Comment by jonathan-s** [comment]
> The context could be evaluated multiple times (at least 2 if you access it in the reflex, or)?

That is indeed correct. We could do better here.

**Comment by JulianFeinauer** [comment]
We could simply store it the first time we evaluate it and always return that then, or?

**Pull request merged**
